### ISSUE TITLE
when open source code 

### ISSUE THREAD

**Issue by yuan-zm** [martianxiu/DiffusionUnit#1]
Hi, @martianxiu: 
Thank you for great work, when open the source code?

**Comment by TankardYegga** [comment]
I have the same doubt. Would it be so nice to tell us a time point that we could check later?

**Comment by martianxiu** [comment]
Hi guys, sorry for the delay, we have uploaded some of the code (not all yet). Hope it helps.

**Comment by yuan-zm** [comment]
Thank you for your sharing.

**Comment by good-job-hard-work** [comment]
Hi, @martianxiu:
Thank you for great work, when open the source code about Part Seg?
