### ISSUE TITLE
Detail for the model training on ShapeNetPart dataset

### ISSUE THREAD

**Issue by Doraemon321** [martianxiu/DiffusionUnit#4]
Hi, can you provide the detail model config when training on ShapeNetPart dataset?
I used the config file 'config/s3dis/res.yaml' to build the model and trained it on ShapeNetPart dataset. But I can't achieve the reported results.

**Comment by martianxiu** [comment]
Hi, thanks for your interest in our work! I just uploaded the config file for the ShapeNetPart dataset. Please check it and let us know if there are any problems.

**Comment by Doraemon321** [comment]
> Hi, thanks for your interest in our work! I just uploaded the config file for the ShapeNetPart dataset. Please check it and let us know if there are any problems.

Thank you for your prompt reply. But there are still some other problems. The module 'robust_laplacian_unit' is mentioned in the config file, but the file ‘model/blocks.py’ does not explain how this module is implemented. Could you update the file to solve this problem?

**Comment by martianxiu** [comment]
> > Hi, thanks for your interest in our work! I just uploaded the config file for the ShapeNetPart dataset. Please check it and let us know if there are any problems.
> 
> Thank you for your prompt reply. But there are still some other problems. The module 'robust_laplacian_unit' is mentioned in the config file, but the file ‘model/blocks.py’ does not explain how this module is implemented. Could you update the file to solve this problem?

Oh, I am sorry I forgot to replace "robust_laplacian_unit" with "diffusion_unit" 😅 . It is just another name for the diffusion unit. I've updated the config file.

**Comment by Doraemon321** [comment]
Thank you for your patient response. I have reproduced the training process. 
At present, the performances I have obtained on the ShapeNetPart dataset are ImIoU 86.4% and CmIoU 84.2% (without voting).
The differences in performance compared to those described in the paper may be due to differences in equipment and other reasons.

**Comment by neverstoplearn** [comment]
> Thank you for your patient response. I have reproduced the training process. At present, the performances I have obtained on the ShapeNetPart dataset are ImIoU 86.4% and CmIoU 84.2% (without voting). The differences in performance compared to those described in the paper may be due to differences in equipment and other reasons.

Hi, I meet some question to train shapenet_part on the model, can you share how to load and precess the shapenet_part dataset,thanks.

**Comment by Doraemon321** [comment]
> > Thank you for your patient response. I have reproduced the training process. At present, the performances I have obtained on the ShapeNetPart dataset are ImIoU 86.4% and CmIoU 84.2% (without voting). The differences in performance compared to those described in the paper may be due to differences in equipment and other reasons.
> 
> Hi, I meet some question to train shapenet_part on the model, can you share how to load and precess the shapenet_part dataset,thanks.

This code repository only has processing methods for the S3DIS dataset and not for the ShapeNetPart dataset. When I reproduced the code before, I only used the network structure part, and the code for processing the dataset was from the CurveNet code repository. Of course, you can also refer to the processing methods of other networks.

**Comment by neverstoplearn** [comment]
> > > Thank you for your patient response. I have reproduced the training process. At present, the performances I have obtained on the ShapeNetPart dataset are ImIoU 86.4% and CmIoU 84.2% (without voting). The differences in performance compared to those described in the paper may be due to differences in equipment and other reasons.
> > 
> > 
> > Hi, I meet some question to train shapenet_part on the model, can you share how to load and precess the shapenet_part dataset,thanks.
> 
> This code repository only has processing methods for the S3DIS dataset and not for the ShapeNetPart dataset. When I reproduced the code before, I only used the network structure part, and the code for processing the dataset was from the CurveNet code repository. Of course, you can also refer to the processing methods of other networks.

thanks
